version: "3.3"

networks:
  sdinc_over:
    external:
      name: "sdinc_over"
  traefik_net:
    external:
      name: "traefik_net"
      
services:
  # docker pull jaegertracing/all-in-one:1
  jaeger:
    image: jaegertracing/all-in-one:1.16
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"
    networks:
      - traefik_net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.jaeger.rule=PathPrefix(`/jaeger`)"
        - "traefik.http.routers.jaeger.service=jaeger"
        - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
        
  traefik:
    image: "traefik:v2.1"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      #- "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.docker.swarmMode=true"
      - "--entrypoints.web.address=:91"
      - "--entrypoints.web=true"
      - "--providers.docker.network=traefik_net"
      # test config
      - "--tracing=true"
      - "--tracing.jaeger=true"
      # - "--tracing.jaeger.samplingType=const"
    ports:
      - "91:91"
      - "92:8080"
    networks:
      - traefik_net
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "containous/whoami"
    networks:
      - traefik_net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=PathPrefix(`/whoami`)"
        - "traefik.http.routers.whoami.entrypoints=web"
        - "traefik.http.routers.whoami.service=whoami"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
